trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      displayName: 'Install dependencies'
      inputs:
        script: |
          sudo apt-get update
          sudo apt-get install -y maven chromium-browser
    - task: CmdLine@2
      displayName: 'Run tests'
      inputs:
        script: |
          mvn clean surefire-report:report
          mvn site -DgenerateReports=false
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: './target/site/'
        ArtifactName: 'drop'
        publishLocation: 'Container'